#!/bin/bash
ssh pi@RMTZ3051 ./.continuousStartupScript.sh
ssh pi@RMTZ3052 ./.continuousStartupScript.sh
ssh pi@RMTZ3053 ./.continuousStartupScript.sh
ssh pi@RMTZ3054 ./.continuousStartupScript.sh
ssh pi@RMTZ3055 ./.continuousStartupScript.sh
ssh pi@RMTZ3056 ./.continuousStartupScript.sh
ssh pi@RMTZ3057 ./.continuousStartupScript.sh
ssh pi@RMTZ3058 ./.continuousStartupScript.sh
ssh pi@RMTZ3059 ./.continuousStartupScript.sh
ssh pi@RMTZ3060 ./.continuousStartupScript.sh
ssh pi@RMTZ3061 ./.continuousStartupScript.sh
ssh pi@RMTZ3062 ./.continuousStartupScript.sh
ssh pi@RMTZ3063 ./.continuousStartupScript.sh
ssh pi@RMTZ3064 ./.continuousStartupScript.sh
ssh pi@RMTZ3065 ./.continuousStartupScript.sh
ssh pi@RMTZ3066 ./.continuousStartupScript.sh
ssh pi@RMTZ3067 ./.continuousStartupScript.sh
ssh pi@RMTZ3068 ./.continuousStartupScript.sh
ssh pi@RMTZ3069 ./.continuousStartupScript.sh
ssh pi@RMTZ3070 ./.continuousStartupScript.sh
ssh pi@RMTZ3071 ./.continuousStartupScript.sh
ssh pi@RMTZ3072 ./.continuousStartupScript.sh
ssh pi@RMTZ3073 ./.continuousStartupScript.sh
ssh pi@RMTZ3074 ./.continuousStartupScript.sh
ssh pi@RMTZ3075 ./.continuousStartupScript.sh
ssh pi@RMTZ3076 ./.continuousStartupScript.sh
ssh pi@RMTZ3077 ./.continuousStartupScript.sh
ssh pi@RMTZ3078 ./.continuousStartupScript.sh
ssh pi@RMTZ3079 ./.continuousStartupScript.sh
ssh pi@RMTZ3080 ./.continuousStartupScript.sh
ssh pi@RMTZ3081 ./.continuousStartupScript.sh
ssh pi@RMTZ3082 ./.continuousStartupScript.sh
ssh pi@RMTZ3083 ./.continuousStartupScript.sh
ssh pi@RMTZ3084 ./.continuousStartupScript.sh
ssh pi@RMTZ3085 ./.continuousStartupScript.sh
ssh pi@RMTZ3086 ./.continuousStartupScript.sh
ssh pi@RMTZ3087 ./.continuousStartupScript.sh
ssh pi@RMTZ3088 ./.continuousStartupScript.sh
ssh pi@RMTZ3089 ./.continuousStartupScript.sh
ssh pi@RMTZ3090 ./.continuousStartupScript.sh
ssh pi@RMTZ3091 ./.continuousStartupScript.sh
ssh pi@RMTZ3092 ./.continuousStartupScript.sh
ssh pi@RMTZ3093 ./.continuousStartupScript.sh
ssh pi@RMTZ3094 ./.continuousStartupScript.sh
ssh pi@RMTZ3095 ./.continuousStartupScript.sh
ssh pi@RMTZ3096 ./.continuousStartupScript.sh
ssh pi@RMTZ3097 ./.continuousStartupScript.sh
ssh pi@RMTZ3098 ./.continuousStartupScript.sh
ssh pi@RMTZ3099 ./.continuousStartupScript.sh

