version: '3'
services:
    web:
        build: ./Backend
        restart: always
        working_dir: /dir
        volumes:
            - ./Backend:/dir
        environment:
            - FLASK_APP=app
            - FLASK_ENV=development
        ports:
            - "80:5000"
        depends_on:
            - mongo
        
        command: python -m flask run --host=0.0.0.0 
               
    mongo:
        image: mongo
        restart: always        
        ports:
            - "27017:27017"
        volumes:
            - ./Database:/data/db
    
    
