version: '3'
services:
    nginx:
        image: nginx:1.13
        volumes:
        - "./app:/var/www/html"
        - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
        - "800:80"
        depends_on:
        - web
    web:
        build: ./Backend
        restart: always
        working_dir: /dir
        volumes:
            - ./Backend:/dir
        environment:
            - FLASK_APP=app
            - FLASK_ENV=development
        ports:
            
            - "443:443"
        depends_on:
            - mongo
            - mqtt
        
        command: python -m flask run --host=0.0.0.0 
    
    mqttmanager:
        build: ./mqttmanager
        restart: always
        working_dir: /dir
        volumes:
            - ./mqttmanager:/dir
        depends_on:
            - mongo
            - mqtt
        
        command: python main.py
               
    mongo:
        image: mongo
        restart: always              
        ports:
            - "27017:27017"
        volumes:
            - ./db_backup:/db_backup   
            - ./Database:/data/db
    
    theia:
        image: theiaide/theia-python
        ports:
           - "3001:3000"
        volumes:
           - ./:/home/project
    
    mongoide:
        image: mongo-express
        volumes:
            - ./db_backup:/db_backup
        ports:
            - "8081:8081"
        links:
            - mongo
        environment:           
            - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
            - ME_CONFIG_MONGODB_SERVER=mongo 
    nodered:
        image: nodered/node-red-docker
        volumes:
            - ./nodered:/data
        ports:
            - "1880:1880"
        links:
            - mongo
            - web
            - mqtt
    mqtt:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
                - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
                - ./mqtt/logs:/mosquitto/log
                - ./mqtt/data:/mosquitto/data
   